### ISSUE TITLE
Fix employee popup on experience graph

### ISSUE THREAD

**Issue by bendycode** [bendyworks/payroll#193]
Currently shows like:
Tim:
Here: 5 years, 4 months
Prior: 96 months direct, 3 months indirect
$54000.0 salary

Please correct to:
Tim Allen:
Here: 5 years, 4 months
Prior: 8 years 0 months direct, 0 years 3 months indirect
$54K salary

Changes:

1. Add last name
2. Show years and months for direct and indirect experience
3. Use $54K style dollar formatting, same as in the key to the right of the graph

**Comment by aterrype** [comment]
Fixed by #211
