### ISSUE TITLE
Fix employee popup on salaries graph

### ISSUE THREAD

**Issue by bendycode** [bendyworks/payroll#194]
Currently shows like:
Apr 13, 2013
Nick $63K: 60,000

Please correct to:
Apr 13, 2013
Nick Alexander: $60K

Changes:
1. Add last name
2. Drop current salary from the name label if possible without dropping from the label
   (if difficult, separate into a separate story, and defer for now as not a big deal)
3. Format salary from that point in time using the $60K money format used in the key to the right of the graph.

**Comment by falonofthetower** [comment]
<img width="772" alt="Screen Shot 2020-12-15 at 4 21 38 P@bendycode " src="https://user-images.githubusercontent.com/6103923/102274328-b20a6c00-3ef1-11eb-9c53-39e0095be6a0.png">
@bendycode like so?

**Comment by bendycode** [comment]
@falonofthetower: Super close!
Please restore the day of the month. Knowing the day of the month is actually frequently useful. :) 
I see the month is now spelled out, instead of abbreviated, but I have no strong opinion one way or the other, so leave it however feels best to you.

**Comment by aterrype** [comment]
Fixed by #211
