### ISSUE TITLE
Fix LoggerSilence deprecation warning

### ISSUE THREAD

**Issue by bendycode** [bendyworks/payroll#55]
Running deploy.sh had this output:
DEPRECATION WARNING: Including LoggerSilence is deprecated and will be removed in Rails 6.1. Please use `ActiveSupport::LoggerSilence` instead (called from <top (required)> at /tmp/build_3e54217b2ac1a930d1e1c6e8e5a26b00/config/application.rb:16)

**Comment by wubr** [comment]
The referenced line in the message is where gems are loaded and after throwing a debugger into `ActiveSupport` I think this is courtesy of `rails_12factor`

**Comment by wubr** [comment]
`rails_12factor` includes `rails_stdout_logging`, and that's where `LoggerSilence` is included: https://github.com/heroku/rails_stdout_logging/blob/b21ed3a29748d2fe62ef1f4fe6bda34294a42dc9/lib/rails_stdout_logging/rails.rb#L3

**Comment by wubr** [comment]
[See also](https://github.com/heroku/rails_stdout_logging/pull/33)
