### ISSUE TITLE
Allow free-form strings in the proposed raise field

### ISSUE THREAD

**Issue by bendycode** [bendyworks/payroll#57]
On the Planning screen:

Previous and Current columns format salaries like "$44K".
Typing "$44K" into the Proposed Raise field and tabbing out keeps the entered "$44K" at first, then when the page is refreshed, or you leave and return, the page shows "0.0" and the entered amount is lost. If I enter "44K" instead, it's converted to "44.0". Let's make this remember the "$44K", just like it was entered.

Perhaps changing the field to a string is a fine solution. Wanted to define the desired behavior change first and foremost though.

**Comment by bendycode** [comment]
@aterrype: I edited this to more cleanly focus on the desired behavior change, instead of the classic pitfall of specifying an assumed implementation. :)

**Comment by aterrype** [comment]
I confirmed that changing the field to a string will achieve the desired result, and I think that makes sense as a short-term fix for the issue. In the long term, it would be nice to convert that data to a numeric format and display it as like the other salary fields. That being said, we don't actually do anything with the proposed raise data aside from displaying it in the planning table, so I think we can put off that change for now. (Having it be a string does also mean that sorting only works if all the proposed raises have the same format, but in practice they probably would.)
